[project]
name = "cheatsheet-gen"
version = "0.1.0"
description = "A simple cheatsheet generator written in Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "markdown>=3.8.2",
    "pymupdf>=1.26.3",
]
